### ISSUE TITLE
Finish the game

### ISSUE THREAD

**Issue by nasivuela** [Adalab/e-s2-evaluacion-intermedia-inmasalcedo#1]
Really cool job @inmasalcedo  !!!

Here you have some tips to improve the exercise:

- [x] Define a good structure of folders and files for the project
- [x] Use a `label` to define the content of the input
- [x] Connect the label to the input using the `for` attribute of the label and the `id` of the input
- [x] Use placeholder attribute instead of value one to show a field's hint
- [x] Enable Strict mode by writing 'use strict' at the beginning of the js document
- [x] Generate and save the random number when the page loads. Right now you are doing it every time the user clicks the button, so the number keeps changing and it makes the game too complex.
- [x] Remember to convert input value string to a number
- [x] Use `===` instead of `==` for comparisons
- [ ] Extract the feedback painter to a function
- [x] Define the logic to make the counter work
- [x] Indent and avoid extra white spaces to improve readability and avoid bugs
- [x] Remove commented code

Let me know if you have any doubts ;)

Go for it!!

**Comment by inmasalcedo** [comment]
Hi Nasivuela!

I adjusted all the issues that you mentioned, let me know if there are further adjustments.

Thank you so much of the feedback!

**Comment by nasivuela** [comment]
Great @inmasalcedo !!!

I'm closing this, but if you want more challenges:
- You are writing many times `textElement.innerHTML = 'something';`, so you could extract it to a function ;)
- What about adding a reset feature?
- Responsive!

![](https://media.giphy.com/media/l0MYDSv9mzn6Rar8A/giphy.gif)
